MYSQLPARAMS: autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull

spring:
  profiles:
    active: ${ENVIRONMENT_MAIN:debug}

---
spring: 
  profiles: debug
server:
  port: 12008
redis:
  host: 192.168.10.128
  port: 6379
datasource:
  url: jdbc:mysql://192.168.10.128:3306/pihy?${MYSQLPARAMS}
  username: root
  password: root

    
---
spring: 
  profiles: grey
  
---
spring: 
  profiles: product
